from core.fingerprint import generate


class TestFingerprintGenerate:
    def test_generates_md5_hex_string(self):
        t = {
            "datetime": "2024-01-15 12:00:00",
            "amount": -50.00,
            "description": "Coffee",
        }
        result = generate(t)
        assert isinstance(result, str)
        assert len(result) == 32  # MD5 hex digest

    def test_same_inputs_produce_same_fingerprint(self):
        t = {
            "datetime": "2024-01-15 12:00:00",
            "amount": -50.00,
            "description": "Coffee",
        }
        assert generate(t) == generate(t)

    def test_different_amounts_produce_different_fingerprints(self):
        t1 = {
            "datetime": "2024-01-15 12:00:00",
            "amount": -50.00,
            "description": "Coffee",
        }
        t2 = {
            "datetime": "2024-01-15 12:00:00",
            "amount": -51.00,
            "description": "Coffee",
        }
        assert generate(t1) != generate(t2)

    def test_different_descriptions_produce_different_fingerprints(self):
        t1 = {
            "datetime": "2024-01-15 12:00:00",
            "amount": -50.00,
            "description": "Coffee",
        }
        t2 = {"datetime": "2024-01-15 12:00:00", "amount": -50.00, "description": "Tea"}
        assert generate(t1) != generate(t2)

    def test_different_datetimes_produce_different_fingerprints(self):
        t1 = {
            "datetime": "2024-01-15 12:00:00",
            "amount": -50.00,
            "description": "Coffee",
        }
        t2 = {
            "datetime": "2024-01-16 12:00:00",
            "amount": -50.00,
            "description": "Coffee",
        }
        assert generate(t1) != generate(t2)

    def test_fingerprint_matches_data_loader_algorithm(self):
        """Ensure the fingerprint is identical to the one generated by data-loader."""
        import hashlib

        t = {
            "datetime": "2024-01-15 12:00:00",
            "amount": -50.00,
            "description": "GROCERY STORE",
        }
        raw = f"{t['datetime']}|{t['amount']}|{t['description']}"
        expected = hashlib.md5(raw.encode()).hexdigest()
        assert generate(t) == expected
